steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      [
        "-m",
        "rsync",
        "-r",
        "-c",
        "-d",
        "./Circle Shop",
        "gs://www.circlestore.online",
      ]
